const data=[
    {
        question:'5+10',
        option:'51',
        option:'10',
        option:'15',
        option:'510',
        ans:'3'
    },
    {
        question:'6/3',
        option:'1',
        option:'3',
        option:'2',
        option:'6',
        ans:'3'
    },
    {
        question:'2+2/2',
        option:'2',
        option:'4',
        option:'222',
        option:'3',
        ans:'1'
    },
    {
        question:'2*20',
        option:'20',
        option:'40',
        option:'60',
        option:'80',
        ans:'2'
    },
    {
        question:'3+89',
        option:'3',
        option:'89',
        option:'92',
        option:'99',
        ans:'3'
    },

]